#!/bin/bash
# sudo apt-get install ssh
read -p "virtualbox user: " VBOX_USER
read -p "virtualbox port: " VBOX_PORT

scp -P$VBOX_PORT ~/.ssh/id_rsa* supernova $VBOX_USER@localhost:~/
ssh -p $VBOX_PORT $VBOX_USER@localhost
