#!/bin/bash
# sudo apt-get install ssh
echo "virtualbox user:"
read VBOX_USER

echo "virtualbox port:"
read VBOX_PORT

scp -P$VBOX_PORT ~/.ssh/id_rsa* supernova $VBOX_USER@localhost:~/
ssh -p $VBOX_PORT $VBOX_USER@localhost
